
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
float _Time;

float random(float2 seed) {
	return frac(sin(dot(seed, float2(12.9898, 78.233))) * 43758.5453);
}

// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	Result[id.xy] = random(id.xy + _Time);
}
